from flask import Flask, request, jsonify
import face_recognition
import numpy as np
from flask_cors import CORS
import pickle
import os
import uuid

# ======================================================
# Load precomputed embeddings (generated by build_embeddings.py)
# ======================================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PICKLE_PATH = os.path.join(BASE_DIR, "celebrity_encodings.pkl")

print("[INFO] Loading celebrity embeddings from pickle...")
with open(PICKLE_PATH, "rb") as f:
    data = pickle.load(f)

celebrity_encodings = data["encodings"]
celebrity_names = data["names"]
print(f"[✅] Loaded {len(celebrity_encodings)} celebrity faces")


# ======================================================
# Flask app
# ======================================================
app = Flask(__name__)
CORS(app)  # so your Flutter frontend can call the /match endpoint


# ------------------------------------------------------
# Match endpoint
# ------------------------------------------------------
@app.route('/match', methods=['POST'])
def match_celeb():
    """Receives an uploaded image and returns the best matching celebrity."""
    if 'image' not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    algorithm = request.form.get('algorithm', 'hog').lower()
    if algorithm not in ['hog', 'cnn']:
        algorithm = 'hog'

    file = request.files['image']
    temp_filename = f"temp_{uuid.uuid4()}.jpg"
    file.save(temp_filename)

    try:
        # Load input image
        image = face_recognition.load_image_file(temp_filename)
        face_locations = face_recognition.face_locations(image, model=algorithm)
        input_encodings = face_recognition.face_encodings(image, known_face_locations=face_locations)

        if not input_encodings:
            return jsonify({"error": "No face found"}), 400

        # Compare with cached celebrity encodings
        input_encoding = input_encodings[0]
        distances = face_recognition.face_distance(celebrity_encodings, input_encoding)
        best_index = np.argmin(distances)

        match_name  = celebrity_names[best_index]
        similarity  = round((1 - float(distances[best_index])) * 100, 2)

        return jsonify({
            "match_name": match_name,
            "similarity": similarity
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

    finally:
        if os.path.exists(temp_filename):
            os.remove(temp_filename)


# ======================================================
# Run server
# ======================================================
if __name__ == '__main__':
    # Fly.io / Railway normally sets PORT as 8080
    port = int(os.environ.get("PORT", 8080))
    app.run(debug=True, host='0.0.0.0', port=port)